name: ronleezy
favicon: null
layout_spectrum: 0.2817822992801666
typography_spectrum: 0.7994240859989077
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbf7f8'
    - '#332b28'
    - '#e4ae8a'
    - '#7fbfe2'
    - '#0087c1'
  brandStrength: 0.9390111709944904
  lightness: 0.7639571814797819
  saturation: 0.8568217335268855
  rhythmicContrast: 0.7299713459797204
purpose: []
